	
@startuml game manager
/' Guide : https://plantuml.com/en/sequence-diagram '/

/'Connection au jeu et reccupération'/
    Actor Utilisateur


    activate Utilisateur

    Utilisateur -> GameManager : Connection

    activate GameManager

    GameManager -> GameLoader : GetSave

    deactivate GameManager

    activate GameLoader

    GameLoader -> GameManager : NoSave

    deactivate GameLoader

    deactivate Utilisateur

/'
Gestion de la sauvegarde
'/
    
    activate GameManager

    GameManager -> Utilisateur : Create Save

    activate Utilisateur

    Utilisateur -> GameManager : Save Finalized

    deactivate Utilisateur

    GameManager -> GameSaver : Saving

    deactivate GameManager


    Utilisateur -> GameManager : play game

    

activate GameManager

GameManager -> GameTimer : Time Management

GameTimer -> GameManager : Real Time


@enduml