@startuml Classes
Class Tamagotchi

package com.lado.App
{
    Class App
    App--GameModel
    App--GameView
    App--Controller
    View--GameModel
    Controller--GameModel
    Controller--View

    package Model
    {

        class DebugMode
        class GameModel
        {
            + Tamagotchi : tamagotchi
        }
        GameModel-Tamagotchi

        package Tamagotchi{
            class Cat extends Tamagotchi
            class Dog extends Tamagotchi
            class Food{
                
            }
            Food->Tamagotchi
            Need->Tamagotchi

            class Need
            {


            }
            class Robot extends Tamagotchi
            class Sheep extends Tamagotchi
            class Tamagotchi
            {
                String name
                # breed : String
                + favoriteFoods : String[]
                + health : Need
                + alive : boolean
                + energy : Need
                + hunger : Need
                + cleanliness : Need
                + happiness : Need
                + CRITICAL_THRESHOLD : integer
                # protected needs : Need[]
                + void setDefaultStats()
                + Tamagotchi(String name)
                + Tamagotchi() 
                + Boolean scanCritical() 
                + void depleteNeeds(float timeElapsed)
                ----
                + String getName()
                + void setName(String newName)
                ---
                + String getBreed()
                + void setBreed(String newBreed)
                ---
                + void checkHealth()
                + void kill()
                + void hurt(int damage)
                + void heal(int healValue)
                + void setHealth(int newHealth)
                + boolean getAlive()
                + void setAlive(boolean alive)
            }
        }


        package SystemPackage
        {
            class gameLoader
            class gameSaver
            class System
        }
    }

    package View{

        class GameView

        package UIPackage {
            class CarePanel
            class ContenuFenetre
            class DebugFrame
            class debugWindow
            class FenetreGraphique
            class GameFrame
            class NeedBar
            class NeedPanel
            class TamagotchiUI
            class UIBuilder
            class Window
        }
    }

    package Controller {

        class GameController
        class classGameListener
    }

}

















@enduml