	
@startuml game manager
/' Guide : https://plantuml.com/en/sequence-diagram '/

/'Connection au jeu et reccupération'/
    Actor Utilisateur


alt Playing with the tamagotchi

    activate Utilisateur


    Utilisateur -> GameManager : play game
    
    deactivate Utilisateur

    activate GameManager

    GameManager -> GameTimer : Time Management

    GameTimer -> GameManager : Real Time

    activate Utilisateur

    Utilisateur -> GameManager : Save and Quit

    GameManager -> GameSaver : Save Game

    GameManager -> Utilisateur : Game closed

    deactivate Utilisateur

else Leave the tamagotchi behind



    GameManager -> Utilisateur : Dying Tamagotchi

    GameManager -> GameSaver : Tamagotchi dead, Save deleted

    GameManager -> Utilisateur : Game Closed
end

    deactivate GameManager



    


@enduml