	
@startuml game manager
/' Guide : https://plantuml.com/en/sequence-diagram '/

/'Connection au jeu et reccupération'/
    Actor Utilisateur


    activate Utilisateur

    Utilisateur -> GameManager : Connection

    activate GameManager

    GameManager -> GameLoader : GetSave

    deactivate GameManager

    activate GameLoader

    GameLoader -> GameManager : Instance Save created

    deactivate GameLoader

    deactivate Utilisateur

/'
Gestion de la sauvegarde
'/
    
    activate GameManager

    GameManager -> Utilisateur : Charging Save

    activate Utilisateur

    deactivate GameManager

    Utilisateur -> GameManager : play game
    
    deactivate Utilisateur

    activate GameManager

    GameManager -> GameTimer : Time Management

    GameTimer -> GameManager : Real Time

    


@enduml