	
@startuml game manager
/' Guide : https://plantuml.com/en/sequence-diagram '/

/'Connection au jeu et reccupération'/
    Actor Utilisateur


alt Playing with the tamagotchi

    activate Utilisateur

    Utilisateur -> GameView : play game

    activate GameView

    Utilisateur -> GameView : *Quit the game*

    deactivate Utilisateur

    GameView -> TamagotchiController : quitBtn

    deactivate GameView

    activate TamagotchiController 

    TamagotchiController -> GameSaver : Save Game

    TamagotchiController -> GameView

    activate GameView

    GameView -> Utilisateur : Game Closed

    deactivate GameView

else Leave the tamagotchi behind



    TamagotchiController -> GameView : Dying Tamagotchi

    activate GameView

    TamagotchiController -> GameSaver : Tamagotchi dead, Save deleted

    deactivate TamagotchiController

    GameView -> Utilisateur : Game Closed

    deactivate GameView
end

    


@enduml