@startuml usecase

left to right direction

package  "Cas d'utilisation 3"  #white{
        actor "Utilisateur" as user3
        
        usecase "Fin de Partie" as finPart
        usecase "s'occuper Tamagotchi" as occupeTama2
   
        usecase "Délaisser Tamagotchi" as delaisserTama2
        usecase "Mort Tamagotchi" as mortTama2
        usecase "Choisir Action" as choixAction3
        usecase "Validation Action" as validationAction3


     finPart ..> occupeTama2 : <<include>>

        user3 -- finPart

        finPart ..> delaisserTama2 : <<include>>

        mortTama2 .left.> occupeTama2 : <<extend>>
        mortTama2 .right.> delaisserTama2 : <<extend>>
        choixAction3 ..> validationAction3 : <<include>>

        occupeTama2 ..> choixAction3 : <<include>>

}



package "Cas d'utilisation 2" #white{
    actor "Utilisateur" as user2
    usecase "Reprendre une Partie" as repPart
        user2 -- repPart

        usecase "recréer instance Tamagotchi" as recreeInstanc
        repPart ..> recreeInstanc : <<include>>
        usecase "s'occuper Tamagotchi" as occupeTama
        repPart ..> occupeTama : <<include>>


        usecase "Mort Tamagotchi" as mortTama
        mortTama ..> occupeTama : <<extend>>

        usecase "Sauvegarder Partie" as savePartie2
        repPart ..> savePartie2 : <<include>>

        usecase "Charger Partie" as chargPartie
        recreeInstanc ..> chargPartie : <<include>>

        usecase "récupérer fichier de sauvegarde" as recupFichier
        chargPartie ..> recupFichier : <<include>>

        usecase "Choisir Action" as choixAction2
        occupeTama ..> choixAction2 : <<include>>

        usecase "Vérification Validité Action" as validiteAct2
        choixAction2 ..> validiteAct2 : <<include>>

}


package "Cas d'utilisation 1"  #white{
    actor Utilisateur as user1
    usecase "Jouer en créeant une partie" as jcreerPart
    usecase "Créer Tamagotchi" as creeTama
    usecase "Debut Partie" as debPartie
    usecase "Choisir Action" as choixAction1
    usecase "Vérification Validité Action" as validiteAct
    usecase "Sauvegarder Partie" as savePartie
    usecase "Choisir Espêce" as choixEspece
    usecase "Choisir Nom" as choixnom1
    usecase "Remplir Formulaire" as formul
    usecase "créer instance Tamagotchi" as creeInstanc
    user1 -- jcreerPart
    jcreerPart ..> creeTama : <<include>>
    creeTama ..> choixnom1 : <<include>>
    creeTama ..> choixEspece : <<include>>
    choixEspece ..> formul : <<include>>
    choixnom1 ..> formul : <<include>>
    formul ..> creeInstanc : <<extend>>
    jcreerPart ..> debPartie : <<include>>
    choixAction1 ..> validiteAct : <<include>>
    debPartie ..> choixAction1 : <<include>>
    jcreerPart ..> savePartie : <<include>>
}




@enduml